platform:ios,'8.0'
target ‘weexios’ do
    use_frameworks!
    pod 'MBProgressHUD'     #加载提示框
    pod 'SDWebImage' , '~>3.8.2'
    pod 'WeexSDK'
    pod 'WXDevtool', :configurations => ['Debug'] #只在 debug 时引入
    pod 'SocketRocket'

end
